[package]
name = "rest-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum='*'
tokio = { version = "1.29", features = ["full"] }
serde_json = "1"
cargo-watch = "8.4.1"
